### PR TITLE
introduce editorconfig-fix

### PR DESCRIPTION
**Pull request by ro0gr**
second attempt to solve #24 

@twokul @stefanpenner 

todo:
- [ ] support `charset` option
- [x] detect `detectIndent` limits. Do we need to whitelist by some set of known file extensions?
- [x] unit test
- [ ] put `.editorconfig` to the `blprnt` root to prevent inconsistent tests #30

### CODE REVIEW

**Comment by stefanpenner** [comment]
@ro0gr very awesome!

**Comment by ro0gr** [comment]
fyi after some testing I couldn't find any pitfalls in `detect-indent` algorithm it works quite nice for different file types and complex file structures.

**Comment by ro0gr** [comment]
Honestly I don't like an idea to implement a `charset` option right now. Mostly because of my laziness 😋 
Is there any chance that somebody uses anything different than `UTF-8` in the nodejs world?

**Comment by initram** [comment]
For charset conversion you could use iconv-lite. It can handle the encodings supported by editorconfig and more.

**Comment by ro0gr** [comment]
@initram Thank you for the pointer. I'll check it out

**Comment by stefanpenner** [comment]
@ro0gr awesome! Will likely need a rebase now.

**Comment by ro0gr** [comment]
@stefanpenner I've rebased. Please review when you have time.

I've looked at `iconv-lite` like @initram proposed. It looks nice.
Anyway I think it requires to re-think and rewrite some parts of existing code base like file reads(strictly UTF-8). Also if we implement `charset` option we need more advanced integration testing story. 
I don't want to struggle with file encoding in this pr because I don't think it can make any value for anybody 🕳

**Comment by ro0gr** [comment]
closing since it got stale.

**Pull request closed without merging**
